### ISSUE TITLE
Update Forms with Modern text input UI .

### ISSUE THREAD

**Issue by Naushad-dev** [pranjay-poddar/Swasthify#83]
Hello, @pranjay-poddar I want to update the text input in the forms on Hospital Login and Patient Login page Thank You!

![Screenshot (11)](https://user-images.githubusercontent.com/106610708/194091695-ac13de6c-9927-414e-8b07-98ae73401a02.png)

**Comment by pranjay-poddar** [comment]
can you please elaborate?

**Comment by Naushad-dev** [comment]
I will add material design outline text field with animation and smooth animation to the card so it will be more smooth and with material design it will look better. If you have any suggestion i can also consider it too. Thank you !

**Comment by pranjay-poddar** [comment]
Can you improve the current UI only, material design is already in use and it should be decent and easy to use for all age groups of people also since this application is to be used in emergency situations adding too many animations will not be a good idea, you can work on this if it suits the project requirement we'll look into considering your contribution.

**Comment by heysaiyad** [comment]
Sir you give me a chance, I will make it very attractive Page.
